/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aly_roger_hook_JNI */

#ifndef _Included_com_aly_roger_hook_JNI
#define _Included_com_aly_roger_hook_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aly_roger_hook_JNI
 * Method:    nativeTest
 * Signature: ()V
 */

JNIEXPORT void JNICALL Java_com_aly_roger_hook_MainActivity_nativeActivityTest
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
